name: "CI (Integração conteínua): Primeira Action"

on:
  # Ativa esse fluxo de trabalho para cada push ou pull que acontecer apontando para a branch
  page_build

# Definindo o que queremos executar
jobs:
  exemplo: # Job exemplo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world

      - name: Run a list files
        run: ls -la